name: thesis_notebooks
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - xarray
  - dask
  - requests
  - opencv
  - pyproj
  - cf_xarray
  - python-dateutil
  - satpy
  - pyspectral
  - cython
  - matplotlib
  - cartopy
  - jupyter
  - notebook
  - google-cloud-storage
  - libnetcdf<=4.9.1
  - netcdf4
  - arm_pyart
  - cmcrameri
  - palettable
  - pip
  - pip:
     - "--editable=git+https://github.com/w-k-jones/tobac-flow.git@v1.8.1#egg=tobac_flow"
     - "--editable=git+https://github.com/w-k-jones/pyLRT.git#egg=pyLRT"
